### ISSUE TITLE
Agree "message types" with BCIM

### ISSUE THREAD

**Issue by simonneb** [Staff-Alerts/project#13]
**What:** Speak with BCIM colleagues about the message types that are required for Staff Alerts i.e. business continuity messages, corporate comms messages. This links to #3 

**Why:** We can use these "message types" to define possible templates in the service - providing coherent and clear comms to staff.

**Comment by pollysait** [comment]
Table to show:
- message types
- who creates them
- who approves them
- who sends them
- who the recipient groups are

https://defra.sharepoint.com/:x:/s/TrainingPlan/EbCcM9dqOmdInhv91StUW30BtWBCbqdp3EmfITGFcBnRqA?e=pdQXxX

**Comment by pollysait** [comment]
Chris Strong was unaware of other using the service for internal comms messages and what their procedures would be for this. She is going to discuss this further as need to decide if we are happy for it to be used in this way and who would pay for it going forward. I also have a user testing session with Sarah Kitts from Internal Comms where we can find out more about how they use it.
