### ISSUE TITLE
Create high-level UI wireframe design

### ISSUE THREAD

**Issue by simonneb** [Staff-Alerts/project#18]
**What:** Create a high level design flow of the internal (message sending) process and the external (contact management) interface

**Why:** This will help us identify the areas we need to focus on and allow SMEs to see what we are looking to do without committing designs to code.

**Comment by simonneb** [comment]
Initial high-level UI designs are below - internal message sending and external contact maintenance

![staff alerts internal](https://user-images.githubusercontent.com/15308860/93870043-901f9580-fcc4-11ea-8558-211f77c71313.png)
![staff alerts external](https://user-images.githubusercontent.com/15308860/93870048-9150c280-fcc4-11ea-974c-bccde9bc3ac8.png)

We will share these with the SMEs for comment - comments welcome from @pollysait @davidjamesstone @rayhanson

**Comment by davidjamesstone** [comment]
Looks nice and simple.

For the external contact maintenance:

- Is the "Add new contact" verified with a OTP or against Active Directory?
- On "Add new alert", would that present all target groups or just a subset?

**Comment by simonneb** [comment]
> * Is the "Add new contact" verified with a OTP or against Active Directory?

Neither - staff can add any contact. As any number is "linked" to their AD ID, we can see if anyone abuses it. I think OTP might be overkill for this service and the time we have.

> * On "Add new alert", would that present all target groups or just a subset?

All - but grouped by type, for example Areas, Offices, Systems etc.

**Comment by pollysait** [comment]
- Once the approve button is hit, is the message sent?
- Once the message has been sent for approval, can the 'creator' go back in and edit it?
- What happens if its rejected? Assume the message would still be there to see and the 'approver' would ask 'creator' to edit it and resend for approval? 
- What would happen it a message was submitted for approval but its then decided that the message doesn't need to be sent after all - can it be deleted so its no longer in the 'messages ready for sending list'?

**Comment by simonneb** [comment]
v0.1 sent to SMEs for comment - see attached. 

![20200928 SA internal v0 1](https://user-images.githubusercontent.com/15308860/94455345-dab07e80-01aa-11eb-8ef4-a8609a5b1e66.png)
![20200928 SA staff contacts v0 1](https://user-images.githubusercontent.com/15308860/94455355-dbe1ab80-01aa-11eb-9939-4772c2801b18.png)

**Comment by simonneb** [comment]
Designs completed - will update UI designs for MVP +1
