### ISSUE TITLE
Discussions with web ops around build environments, hosting and support.

### ISSUE THREAD

**Issue by davidjamesstone** [Staff-Alerts/project#19]
**What:** 
Engage with AWS WebOps to begin conversations around the environments required for building and hosting.
Depending on how we authenticate users, we may also need to contact Cloud Service Center (Ishmal Marks) to set up an AD Authentication Security Group

**Why:**
So we have a place to publish the applications and services for testing and production.
To enable users to login to the application using their AD username and password

**Comment by simonneb** [comment]
Initial discussions with Dave Blackburn on hosting options for Staff Alerts. Needs more formal chat.

**Comment by simonneb** [comment]
@davidjamesstone to engage with Cloud Service Center (Ishmal Marks) to set up an AD Authentication Security Group
