### ISSUE TITLE
Investigate GOV.UK Platform-as-a-service as an option for hosting

### ISSUE THREAD

**Issue by davidjamesstone** [Staff-Alerts/project#23]
**What:** 
Investigate GOV.UK Platform-as-a-service as an option for hosting as an alternative to traditional DDTS model

**Why:**
We need to understand if it is suitable for our needs, whether we can or should opt for it and what the on-going application support model would look like if we did use it

**Comment by simonneb** [comment]
PaaS MOU has been signed and sent off - we can "go live" when we are ready
