### ISSUE TITLE
Plan subdomains

### ISSUE THREAD

**Issue by simonneb** [Staff-Alerts/project#26]
**What:** we need useful subdomains for the various elements of the service

**Why:** so that staff and users can quickly access the service

**Comment by simonneb** [comment]
Here are the subdomains I think we need . What do you think @davidjamesstone @rayhanson ? When it comes to dev environment - we can just use the "raw" URL that PaaS provides I think. 

- [staff-alerts.environment-agency.gov.uk](staff-alerts.environment-agency.gov.uk) - for future replacement of www.environment-agency.gov.uk/bcm
- [send.staff-alerts.environment-agency.gov.uk](send.staff-alerts.environment-agency.gov.uk) - the internal app for creating, approving and sending a message
- [manage.staff-alerts.environment-agency.gov.uk](manage.staff-alerts.environment-agency.gov.uk) - the staff app for managing their details
- [training.staff-alerts.environment-agency.gov.uk ](training.staff-alerts.environment-agency.gov.uk )- the training app for creating, appriving and sending a message

**Comment by simonneb** [comment]
Also added [docs.staff-alerts.environment-agency.gov.uk ](docs.staff-alerts.environment-agency.gov.uk )- for the guidance documents.

**Comment by simonneb** [comment]
Made a request to the webmaster to see if the domains above would be possible

**Comment by davidjamesstone** [comment]
> Here are the subdomains I think we need . What do you think @davidjamesstone @rayhanson ? When it comes to dev environment - we can just use the "raw" URL that PaaS provides I think.
> 
> * [staff-alerts.environment-agency.gov.uk](staff-alerts.environment-agency.gov.uk) - for future replacement of [www.environment-agency.gov.uk/bcm](http://www.environment-agency.gov.uk/bcm)
> * [send.staff-alerts.environment-agency.gov.uk](send.staff-alerts.environment-agency.gov.uk) - the internal app for creating, approving and sending a message
> * [manage.staff-alerts.environment-agency.gov.uk](manage.staff-alerts.environment-agency.gov.uk) - the staff app for managing their details
> * [training.staff-alerts.environment-agency.gov.uk ](training.staff-alerts.environment-agency.gov.uk)- the training app for creating, appriving and sending a message

In light of the name changes you made @simonneb, I wonder if `manage.staff-alerts.environment-agency.gov.uk` would be better `get.staff-alerts.environment-agency.gov.uk`?

**Comment by davidjamesstone** [comment]
Also, there's a training version of message-web but not for contact-web - any reason? Would it be useful?

**Comment by simonneb** [comment]
> Also, there's a training version of message-web but not for contact-web - any reason? Would it be useful?

Good point @davidjamesstone - i think we have made contact-web as simple as we can that training shouldn't be required. Is there another reasons other than user training that we would need it? Would it be useful for messages-web training do you think?

**Comment by simonneb** [comment]
I've now got the CNAME data needed by the webmaster, which I will share on Monday 26th when I am back in the office

**Comment by simonneb** [comment]
Domains are now set-up although there are issues viewing the pages via the staff-alerts.environment-agency.gov.uk URLs. Direct URLS to PaaS still work fine. I have created a new ticket for MVP+1 to look at working with DDTS to get these new URLs whitelisted on our VPN.
