### ISSUE TITLE
Define user roles for Azure access to messages-web

### ISSUE THREAD

**Issue by simonneb** [Staff-Alerts/project#33]
**What:** Agree the roles and permissions needed in Azure application registration

**Why:** So that we can ensure users have access to the right parts of the application to perform their roles.

**Comment by simonneb** [comment]
@davidjamesstone and @simonneb have created application permissions that need to be created in Azure. @simonneb to take these to DDTS for inclusion in dev and live environments.

**Comment by simonneb** [comment]
Our groups are:

* Editor - this will allow you to create and edit messages - for example Area Base Controllers (ABC)
* Manager - this will allow you to create, edit and approve messages - for example Area Duty Managers (ADM)
* Administration - this gives you all functions including the ability to upload contact lists - for example External Digital Services

@davidjamesstone - I think we need one more:

* Super user - this will allow you to create, edit, approve and **send messages** - for example Incident Communication Services (ICS)

What do you think? In addition we are also going to ask for a Viewer group - that can be used in the future for simple reporting (non-MVP).

**Comment by davidjamesstone** [comment]
I'm not sure . Currently approving a message will immediately send it. There's no process or pages to send a message.
