### ISSUE TITLE
Add support link to contacts-web

### ISSUE THREAD

**Issue by simonneb** [Staff-Alerts/project#40]
**What:** add a contact email address to the footer in contacts-web app

**Why:** so that users can get the support they need if they run into issues

**Comment by davidjamesstone** [comment]
Did we say this was now to be a support email that appears in the footer?
If so, what is the inbox address please?

**Comment by simonneb** [comment]
Yes we did - can yo uuse : imr-enquiries@environment-agency.gov.uk

**Comment by simonneb** [comment]
Added by @davidjamesstone - now closing.
