### ISSUE TITLE
Gather data related to use of Staff Line

### ISSUE THREAD

**Issue by simonneb** [Staff-Alerts/project#5]
**What:** We need to understand the number of calls the Staff Line gets

**Why:** This will allow us to think about appropriate replacement for the future 

**How:** we need to know 

- How frequently is the line called?
- When has it been called in the past?
- Ideally, what interactions the user has with the service

**Comment by LizHills** [comment]
ICS have confirmed they keep no formal log of requests that come in, where from, message type, where to update etc - they do apparently report back each month a total figure of requests (which I've asked for) but this won't include any sent by NCPMS as they log in directly to do this.  

There are currently no messages shown in the sent items on Rant and Rave (these are kept for 30 days and then auto deleted unless archived).

**Comment by LizHills** [comment]
Request from Chris Strong to advise on if we are able to see how many calls have been made to the BCM phone line that is included in the text alert or if this element of the service could be retired.
