### ISSUE TITLE
Plan user testing

### ISSUE THREAD

**Issue by simonneb** [Staff-Alerts/project#7]
**What:** We need to begin  to plan user testing for our development work in later weeks.

**Why:** This will help us understand if we are delivering something of use to our users (staff and message senders). 

How: We need to: 

- Identify staff users
- Identify message message senders
- Identify who approves messages 
- Identify service managers/owners
- Agree what we want to know from them

**Comment by simonneb** [comment]
All ICS users would have access (around 50 staff) to approve messages. Can we arrange user testing through Steph Turner to ensure a good spread of users. Steph offered a run through of the process too.

**Comment by pollysait** [comment]
List of potential user testers
**Staff**
- **Tash Temple-Cox**
- **Iain Urquhart**
- **Ben Smedley**
- **Ann Plumb**
- **Matt Brennon**
- **Andrew Twigg**

**Creators** 
- **Sarah Hale (ABC)**
- **Rory Sanderson (ABC)**
- **Nicola Vaughan, Tom Evans and Michael Rennie (Click users)**
- Sarah Kitts TBC (Internal Comms)
- NIR (NBC?)

**Approvers**
- **Joe Cuthbertson (ADM**
- **Jeanne Capey (ADM)**
- **Phil Lodge (NDM)**
- Another NDM (Kate Marks has asked for volunteers)

**Senders**
- **James Cowan (ICS)**
- **Jonathan Tyas (ICS)**
- **Ashley Smith (ICS)**
- **Leanne Bramham (ICS)**
- **Alex Haigh (ICS)**
- **John Stevenson (ICS)**

**Comment by pollysait** [comment]
Appointments sent for all those that have confirmed they can help. Spread out across the two weeks. 
Made a start on writing questions to ask them.
