### ISSUE TITLE
Get ICS Knowledge Articles and guidance

### ISSUE THREAD

**Issue by simonneb** [Staff-Alerts/project#8]
**What:** Get copies of the ICS Knowledge articles and guidance from Steph Turner.

**Why:** We will be able to get a better understanding of the existing process for the current service, and look for efficiencies.

**Comment by pollysait** [comment]
Guidance documents have been saved here: https://defra.sharepoint.com/:f:/s/TrainingPlan/EkOrvdpK01hNt5ZEUDlvUCMBzOCAOBrP1CSkw4ZiHKIbHw?e=ia4wgH

Also  includes a summary with a few questions for Steph Turner at ICS
